// <auto-generated />
using System;
using EntityFrameworkPractice.Controllers.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkPractice.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200208195135_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.Cliente", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prestigio")
                        .HasColumnType("int");

                    b.HasKey("PessoaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.ItemVenda", b =>
                {
                    b.Property<int>("ItemVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemVendaId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("ItemVendaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItemVendas");
                });

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientePessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VendedorPessoaId")
                        .HasColumnType("int");

                    b.HasKey("VendaId");

                    b.HasIndex("ClientePessoaId");

                    b.HasIndex("VendedorPessoaId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.Vendedor", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentagemComissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Setor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PessoaId");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.ItemVenda", b =>
                {
                    b.HasOne("EntityFrameworkPractice.Controllers.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("EntityFrameworkPractice.Controllers.Models.Venda", "Venda")
                        .WithMany("ItemVendaList")
                        .HasForeignKey("VendaId");
                });

            modelBuilder.Entity("EntityFrameworkPractice.Controllers.Models.Venda", b =>
                {
                    b.HasOne("EntityFrameworkPractice.Controllers.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClientePessoaId");

                    b.HasOne("EntityFrameworkPractice.Controllers.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorPessoaId");
                });
#pragma warning restore 612, 618
        }
    }
}
